<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6mhg45r\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6mhg45r/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6mhg45r.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6mhg45r\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6mhg45r\appProdProjectContainer([
    'container.build_hash' => '6mhg45r',
    'container.build_id' => '8aeeb423',
    'container.build_time' => 1632602962,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6mhg45r');
